// <auto-generated />
using System;
using MedicalSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicalSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MedicalSystem.Models.Doctor", b =>
                {
                    b.Property<int?>("doctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("doctorId"), 1L, 1);

                    b.Property<int?>("Specialiteid")
                        .HasColumnType("int");

                    b.Property<string>("age")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("birthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("cin")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("imageUser")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("sexe")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("doctorId");

                    b.HasIndex("Specialiteid");

                    b.ToTable("Doctors", "DC");
                });

            modelBuilder.Entity("MedicalSystem.Models.MedicalSpecialities", b =>
                {
                    b.Property<int?>("specId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("specId"), 1L, 1);

                    b.Property<string>("specName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("specId");

                    b.ToTable("MedicSpecialities", "DC");
                });

            modelBuilder.Entity("MedicalSystem.Models.Doctor", b =>
                {
                    b.HasOne("MedicalSystem.Models.MedicalSpecialities", "medicalSpecialities")
                        .WithMany()
                        .HasForeignKey("Specialiteid");

                    b.Navigation("medicalSpecialities");
                });
#pragma warning restore 612, 618
        }
    }
}
